server:
  port: 8080

spring:
  application:
    name: authgate
  datasource:
    url: jdbc:postgresql://localhost:5432/authgate_db
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30m
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

      listeners:
        envers:
          autoRegister: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: javaprogrammer1993@gmail.com
    password: sbckiwyqtjghyptv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 1800000  # 30 min
    refresh-expiration: 86400000 # 24h
  verification:
    code-expiration: 600000 # 10 minutes
  account:
    max-failed-attempts: 5
    lock-time-minutes: 60
  security:
    csrf:
      logout-enabled: true
  file:
    upload-dir: ./photos
  base-url: http://localhost:8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoint:
    cache:
      enabled: true