server:
  port: 8080
  servlet:
    context-path: /authgate

spring:
  application:
    name: authgate
  datasource:
    url: jdbc:postgresql://localhost:5432/authgate_db
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30m
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:

      listeners:
        envers:
          autoRegister: true

  mail:
    host: localhost    #smtp.gmail.com
    port: 1025         #587
    username:          #javaprogrammer1993@gmail.com
    password:          #sbckiwyqtjghyptv
    properties:
      mail:
        smtp:
          auth: false  #true
          starttls:
            enable: false   #true

app:
  jwt:
    secret: YS1zdHJpbmctc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmctZm9yLWpXdC1zaWduaW5n
    expiration: 3600000  # 60 min
    refresh-expiration: 86400000 # 24h
  verification:
    code-expiration: 600000 # 10 minutes
  account:
    lock-time-minutes: 60
  security:
    csrf:
      logout-enabled: true
  file:
    upload-dir: ./photos
  base-url: http://localhost:8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

rate-limiting:
  max-failed-attempts: 5
  refill-duration-minutes: 30

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        aop: TRACE
      validation: TRACE

management:
  endpoint:
    cache:
      enabled: true